### ISSUE TITLE
GetVSyncParametersIfAvailable() failed

### ISSUE THREAD

**Issue by JohnnyLawDGB** [RenzoDD/digibyte-desktop#1]
## Description

When attempting to run the DigiByte Desktop application (version 0.0.0) on Ubuntu 23.04 (Lunar), I encountered multiple `GetVSyncParametersIfAvailable() failed` errors, which prevent the GUI from loading.

## Steps to Reproduce

1. Built the DigiByte Desktop application from source.
2. Navigated to the `dist` directory.
3. Made the AppImage executable using `chmod +x DigiByte\ Desktop-0.0.0.AppImage`.
4. Attempted to run the AppImage using `./DigiByte\ Desktop-0.0.0.AppImage`.

## Expected Behavior

The application should launch, and the GUI should load successfully.

## Actual Behavior

The application appears to launch, but the GUI does not load. Instead, the following errors are logged to the terminal:
[12916:1023/200104.221703:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[12916:1023/200111.609125:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[12916:1023/200438.563066:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
## Environment

- OS: Ubuntu 23.04 (Lunar)
- DigiByte Desktop Version: 0.0.0

**Comment by RenzoDD** [comment]
Which version of NodeJS was used?

**Comment by JohnnyLawDGB** [comment]
Kept getting error messages regarding NodeJS when loading AngularCLI until I set the version to16.14.  I see now you specified 16.20.  Once I get my Linux dev environment back up and running I will attempt with that.

**Comment by JohnnyLawDGB** [comment]
will re-open if issue persists with correct NodeJS version.
